# Generated by Django 3.0.3 on 2020-11-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
